import {Actor} from 'apify'; import {CheerioCrawler,Dataset} from 'crawlee'; import target from '../target.json' with {type:'json'};
const sleep=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
const getPath=(value,path)=>path.split('.').reduce((current,key)=>current?.[key],value);
async function fetchPermitted(url, options){if(!target.source.allowedHosts.includes(new URL(url).hostname))throw new Error('Host outside allowlist');for(let attempt=0;attempt<3;attempt++){const response=await fetch(url,options);if(response.ok)return response;if(response.status!==429&&response.status<500)throw new Error(`Source returned ${response.status}`);await sleep(500*(attempt+1));}throw new Error('Source unavailable after bounded retries');}
await Actor.init();
try {const input=(await Actor.getInput())??{};const maxItems=Math.min(input.maxItems??target.output.maxItemsDefault,target.output.maxItemsHard);const urls=input.startUrls??target.request.startUrls;const seen=new Set();let count=0;
if(target.source.kind==='json-api'){for(const url of urls){const response=await fetchPermitted(url,{method:target.request.method,headers:{accept:'application/json','content-type':'application/json',...(target.request.headers??{})},body:target.request.method==='POST'?JSON.stringify(target.request.body):undefined});const data=await response.json();const rows=Array.isArray(data)?data:(data.results??data.items??[]);for(const row of rows){if(count>=maxItems)break;const item=Object.fromEntries(Object.entries(target.extraction.fields).map(([key,path])=>[key,getPath(row,path)]));const identity=target.extraction.identityFields.map(key=>String(item[key]??'')).join('|');if(!identity||seen.has(identity))continue;seen.add(identity);await Actor.pushData(item);count++;}}}
else {const crawler=new CheerioCrawler({maxConcurrency:target.request.maxConcurrency,maxRequestsPerMinute:target.request.rateLimitPerMinute,async requestHandler({request,$,enqueueLinks}){if(!target.source.allowedHosts.includes(new URL(request.url).hostname))throw new Error('Host outside allowlist');for(const element of $(target.extraction.itemSelector).toArray()){if(count>=maxItems)return;const item=Object.fromEntries(Object.entries(target.extraction.fields).map(([key,selector])=>[key,$(element).find(selector).first().text().trim()]));const identity=target.extraction.identityFields.map(key=>String(item[key]??'')).join('|');if(!identity||seen.has(identity))continue;seen.add(identity);await Actor.pushData(item);count++;}if(target.extraction.nextPageSelector&&count<maxItems)await enqueueLinks({selector:target.extraction.nextPageSelector});}});await crawler.run(urls);}}
finally {await Actor.exit();}
